### ISSUE TITLE
executable file (test1) in ubuntu

### ISSUE THREAD

**Issue by ydh6226** [influxdb/influxdb-c#10]
Hi my influxdb version is 1.7.x and i am trying to use it with c.
I have pulled the files and made an executable test1 file to make a database with the code.
But unfortunately when i execute the file it doesn't happen anything. 
Will it have an solution to solve it? 
Thank you

**Comment by russorat** [comment]
@ydh6226 thanks for opening this. Looks like this repo hasn't been touched in quite a while and isn't compatible with the latest influxdb. I'll work on getting this repo archived to avoid confusion, but you might have more luck with this community maintained library: https://github.com/orca-zhang/influxdb-c
