### ISSUE TITLE
Gcc link library curl error

### ISSUE THREAD

**Issue by scarface21** [influxdb/influxdb-c#4]
I try to compile an example and use the library
gcc server.c -o server -linfluxdb

and the error appears in the compiled libinfluxdb.so library, linking the curl library

/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_escape'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_free'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_getinfo'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_perform'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_init'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_setopt'
/usr/local/lib/libinfluxdb.so: undefined reference to `curl_easy_cleanup'

How do you install curl library?

I used the standard apt-get install way.

Note: The influxdb-c compiles with no error and on the configure process it even finds the curl options.
and the ldd on /usr/local/lib/libinfluxdb.so gives this

linux-vdso.so.1 =>  (0x00007fffeaf2e000)
	libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x00007fd3f5aec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd3f5724000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd3f5f19000)

so maybe not a good linking with curl?
Thank you

**Comment by radcheb** [comment]
I have had the same problem, and the solution was to link libcurl as you said by adding the  "-lcurl" flag in the makefile or directly in gcc command:
gcc server.c -o server -linfluxdb -lcurl

**Comment by akiskourtis** [comment]
Yes that worked! Thank you for your response!
